import { Koh_Santepheap } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/ui/LayoutWrapper";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "@/components/ui/sonner";

export const kohSantepheap = Koh_Santepheap({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "LeeLeesCreationz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kohSantepheap.className}>
        <CartProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
          <Toaster
            theme="light"
            richColors
            toastOptions={{
              style: {
                boxShadow:
                  "0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)",
              },
            }}
          />
        </CartProvider>
      </body>
    </html>
  );
}
